spring:
  config:
    activate:
      on-profile: dev, prod, test
  mail:
    host: smtp.gmail.com
    port: 587
    username: medica.plus.email@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jwt:
    secret:
    expiration-time-millis: 604800000
springdoc:
  api-docs:
    path: /api-docs
business:
  schedule:
    visit-duration-mins: 15
    working-day:
      begins: "08:00"
      duration-hours: 8
    break:
      begins: "13:00"
      duration-mins: 30
  data:
    page-size: 5
    phone-number-prefix: "+48"
server:
  servlet:
    context-path: /api/v1
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/clinic
    username: root
    password: i?u.M7afDGo)hZ=2Ny]V
  custom:
    security:
      request-matchers:
        permit-all: >
          POST /users/activate,
          GET /authenticate,
          POST /register/patient,
          GET /doctors/specialization/**,
          GET /doctors/department/**,
          GET /appointments/availability/**,
          GET /departments,
          GET /holidays,
          GET /specializations,
          GET /swagger-ui.html,
          GET /swagger-ui/**,
          GET /api-docs/**
        optional-auth:
          POST /appointments/patient
    frontend-base-url: http://localhost:4200
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: trace
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/clinic
    username: root
    password: i?u.M7afDGo)hZ=2Ny]V
  custom:
    security:
      request-matchers:
        permit-all: >
          POST /users/activate,
          GET /authenticate,
          POST /register/patient,
          GET /doctors/specialization/**,
          GET /doctors/department/**,
          GET /appointments/availability/**,
          GET /departments,
          GET /holidays,
          GET /specializations,
        optional-auth:
          POST /appointments/patient
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: test
  custom:
    security:
      request-matchers:
        permit-all: >
          POST /users/activate,
          GET /authenticate,
          POST /register/patient,
          GET /doctors/specialization/**,
          GET /doctors/department/**,
          GET /appointments/availability/**,
          GET /departments,
          GET /holidays,
          GET /specializations,
          GET /swagger-ui.html,
          GET /swagger-ui/**,
          GET /api-docs/**,
          GET /h2-console,
          GET /h2-console/**
        optional-auth:
          POST /appointments/patient
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER;
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    defer-datasource-initialization: true
test:
  server:
    baseUrl: http://localhost:8082/api/v1
server:
  port: 8082