# JDBC properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clinic
    username: root
    password: i?u.M7afDGo)hZ=2Ny]V
  mail:
    host: smtp.gmail.com
    port: 587
    username: medica.plus.email@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  custom:
    security:
      permitted-matchers: >
        POST /users/activate,
        GET /authenticate,
        POST /register/**,
        GET /doctors,
        GET /appointment/availability/**,
        GET /departments
  jwt:
    secret:
    expiration-time-millis: 604800000

server:
  servlet:
    context-path: /api/v1

# Logging
# spring:
#   jpa:
#     show-sql: true
# logging:
#   level:
#     org.hibernate.SQL: debug
#     org.hibernate.type.descriptor.sql: trace
logging:
  level:
    org.springframework.security: DEBUG

# Business logic properties
data:
  phone-number-prefix: "+48"