# JDBC properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clinic
    username: root
    password: i?u.M7afDGo)hZ=2Ny]V

server:
  servlet:
    context-path: /api/v1

# Logging
# spring:
#   jpa:
#     show-sql: true
# logging:
#   level:
#     org.hibernate.SQL: debug
#     org.hibernate.type.descriptor.sql: trace
logging:
  level:
    org.springframework.security: DEBUG

# Business logic properties
data:
  phone-number-prefix: "+48"